[build]
  command = "npm test && npm run build"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reset"
  to = "/reset.html"
  status = 200
