name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@master
      with:
        node-version: 12.0.0

    - name: Install dependencies
      run: npm ci
      
    - name: Build the project
      run: npm run build
      
    - name: Run the unit tests
      run: npm test
